services:
  - type: web
    name: kashmakr-gig_ba5014d2-t1002
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
